FROM centos
RUN yum install -y epel-release
RUN yum install -y wget
RUN yum -y install openssh-clients 
RUN mkdir /root/video
RUN wget http://103.114.163.62/down/97753/me/uk/lesson001.rar
RUN wget http://103.114.163.62/down/97753/me/uk/lesson002.rar 
RUN wget http://103.114.163.62/down/97753/me/uk/lesson003.rar 
RUN wget http://103.114.163.62/down/97753/me/uk/lesson004.rar
RUN wget http://103.114.163.62/down/97753/me/uk/lesson005.rar
